/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package calculadora;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author saqui
 */
public class historial extends javax.swing.JInternalFrame {

    /**
     * Creates new form historial
     */
     public historial() {
        initComponents();
        cargarHistorial();
    }
    
    private void cargarHistorial() {
        StringBuilder sb = new StringBuilder();
        try (BufferedReader lector = new BufferedReader(new FileReader("bitacoraCalculadora.txt"))) {
            String linea;
            while ((linea = lector.readLine()) != null) {
                sb.append(linea).append(System.lineSeparator());
            }
        } catch (IOException excepcion) {
            excepcion.printStackTrace();
        }
        txt_mostrar.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_mostrar = new javax.swing.JTextPane();

        setClosable(true);
        setIconifiable(true);
        setTitle("HISTORIAL");
        setPreferredSize(new java.awt.Dimension(325, 378));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jScrollPane1.setViewportView(txt_mostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txt_mostrar;
    // End of variables declaration//GEN-END:variables
}
