/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author saqui
 */
public class ayuda extends javax.swing.JInternalFrame {
    
    

    /**
     * Creates new form ayuda
     */
    public ayuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MENU AYUDA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(325, 378));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Operaciones Básicas\n\nSuma:\nIngresa el primer número en la pantalla.\nPresiona el botón +.\nIngresa el segundo número.\nPulsa el botón = para obtener el resultado.\n\nResta:\nIntroduce el primer número.\nPresiona el botón -.\nIntroduce el segundo número.\nPulsa el botón = para ver el resultado.\n\nMultiplicación:\nEscribe el primer número.\nPulsa el botón *.\nIntroduce el segundo número.\nPresiona = para calcular el resultado.\n\nDivisión:\nIntroduce el primer número.\nPulsa el botón /.\nEscribe el segundo número.\nPresiona = para ver el resultado.\n\n2. Historial de Operaciones\n\nVisualizar Historial:\nHaz clic en el botón \"Historial\" en la interfaz de la \ncalculadora.\nSe abrirá una ventana que muestra las operaciones \nrealizadas recientemente.\n\n3. Reiniciar la Calculadora\nHaz clic en \"Opciones\" en la interfaz de la calculadora.\nSelecciona \"Nuevo\" del menú desplegable para \nborrar la pantalla y reiniciar la calculadora.\n\n4. Cerrar la Aplicación\nHaz clic en la \"X\" ubicada en la esquina superior \nderecha de la ventana de la calculadora.\nLa aplicación se cerrará automáticamente.\n");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}

